"""empty message

Revision ID: 48793ba46cf0
Revises: b28068854b89
Create Date: 2022-08-27 21:53:33.200705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48793ba46cf0'
down_revision = 'b28068854b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assets', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'group_id')
    # ### end Alembic commands ###
