"""empty message

Revision ID: 8cf9e23eb9e6
Revises: 48793ba46cf0
Create Date: 2022-08-27 22:03:04.182234

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8cf9e23eb9e6'
down_revision = '48793ba46cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('token', sa.String(length=150), nullable=True))
    op.drop_column('group', 'join_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('join_token', mysql.VARCHAR(length=150), nullable=True))
    op.drop_column('group', 'token')
    # ### end Alembic commands ###
