"""empty message

Revision ID: b28068854b89
Revises: 
Create Date: 2022-08-27 21:47:47.606831

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b28068854b89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GroupAssets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GroupAssets',
    sa.Column('GroupID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('AssetID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['AssetID'], ['assets.id'], name='GroupAssets_ibfk_2'),
    sa.ForeignKeyConstraint(['GroupID'], ['group.id'], name='GroupAssets_ibfk_1'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
