version: '3'
services:
  product-service:
      build: ./app/
      restart: always
      volumes:
        - ./app/:/usr/src/app/
      ports: 
        - 5000:5000
      environment: 
        PORT: 5000
        FLASK_DEBUG: 1
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
